name: x_icon
description: part of flutter remote-ui project. dynamic and remote icon loader for flutter
version: 0.0.4
author: softmarshmallow <woojoo@softmarshmallow.com>
homepage: https://github.com/softmarshmallow/remote-ui/tree/master/flutter/packages/x_icon

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.10.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  json_serializable: ^4.1.1

flutter:
