name: x_action
description: a flutter uri based dynamic action handler
version: 0.0.1+4
homepage: https://github.com/softmarshmallow/dynamic/tree/master/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <2.10.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1

  x_uri:
    ^0.0.1+1
    # path: ../x_uri

  # FIXME remove this before release
  # flutter_modular: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.1
  build_runner: ^2.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
